import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

import React from 'react';
import './flexbox.css';
import Menu from "./components/header"

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <header className="bg-slate-900 text-white py-4">
          <div className="flex justify-center items-center">
            <h1 className="text-3xl font-bold">Todo App</h1>
          </div>
        </header>
        {children}
        <footer className="bg-slate-900 text-shadow-white text-center"><h1 className="text-3xl font-bold ">END..</h1></footer>
      </body>
    </html>
  );
}
